In [10]:
allthings = {}
for val in range(1000):
    import numpy as np

    NUM_BEBS = 2000

    buses = np.random.dirichlet(np.ones(10), size=10000)
    for i in range(len(buses)):
        buses[i] = [round(x*(NUM_BEBS-10))+1 for x in buses[i]]

    buses = [x for x in buses if sum(x) == NUM_BEBS]



    def model(GRANT, AVG_DISTANCE, DISCOUNT_RATE, DIESEL_COST, DIESEL_EFFICIENCY, DIESEL_FUEL_PRICE,
            DIESEL_FUEL_INCREASE, DIESEL_MAINTENANCE, BEB_COST, BEB_EFFICIENCY, BEB_FUEL_PRICE,
            BEB_MAINTENANCE, BEB_FUEL_INCREASE, BEB_DEMAND_CHARGE, BEB_RESALE, CHARGER_COST, 
            CHARGER_INSTALLATION, CHARGER_PEAK_DRAW, YEARS):
        # LIFETIME = 12
        CHARGER_EFFICIENCY = 0.9
        dcf = 0

        dcf = ((DIESEL_COST-BEB_COST) - CHARGER_COST - CHARGER_INSTALLATION + GRANT)  # upfront costs 
        # dcf += NUM_BEBS * (DIESEL_COST*DIESEL_RESALE)
        # print(dcf)
        for year in range(YEARS):
            projected_discount = (1+DISCOUNT_RATE)**year
            maintenance = (DIESEL_MAINTENANCE-BEB_MAINTENANCE)*AVG_DISTANCE
            fuel = (DIESEL_EFFICIENCY*DIESEL_FUEL_PRICE*((1+DIESEL_FUEL_INCREASE)**year)
                    -(2-CHARGER_EFFICIENCY)*BEB_EFFICIENCY*BEB_FUEL_PRICE*((1+BEB_FUEL_INCREASE)**year))*AVG_DISTANCE
            demand = CHARGER_PEAK_DRAW*BEB_DEMAND_CHARGE
            dcf += (maintenance+fuel-demand)/projected_discount
            
            # print("Year:", year+1, "DCF:", dcf)
            
        #  print(dcf)
        dcf += ((BEB_COST*BEB_RESALE))/(1+DISCOUNT_RATE**YEARS)
        return dcf



    GRANT_TOTAL = 10000000

    out = []

    for sample in buses: 
        total = 0 
        
        values = {
            'GRANT': 375000,
            'AVG_DISTANCE': 26980.64,
            'DISCOUNT_RATE': 0.0249,
            'DIESEL_COST': 435000,
            'DIESEL_EFFICIENCY': 0.227,
            'DIESEL_FUEL_PRICE': 4.366,
            'DIESEL_FUEL_INCREASE': 0.014,
            'DIESEL_MAINTENANCE': 0.49,
            'BEB_COST': 770000 ,
            'BEB_EFFICIENCY': 2.15,
            'BEB_FUEL_PRICE': 0.1256,
            'BEB_MAINTENANCE': 0.14,
            'BEB_FUEL_INCREASE': 0.024,
            'BEB_DEMAND_CHARGE': 3.45,
            'BEB_RESALE': 0.15,
            'CHARGER_COST': 50000,
            'CHARGER_INSTALLATION': 17050,
            'CHARGER_PEAK_DRAW': 70,
            'YEARS': 10,
        }
        
        for amount in sample:
            values['GRANT'] = GRANT_TOTAL/amount
            total += amount * model(*values.values())
            values['DIESEL_FUEL_PRICE'] *= (1+values['DIESEL_FUEL_INCREASE'])
            values['BEB_FUEL_PRICE'] *= (1+values['BEB_FUEL_INCREASE'])
            values['BEB_COST'] *= 0.95
            values['YEARS'] -= 1
        
        out.append(total)

    allthings[max(out)] = buses[out.index(max(out))]

In [17]:
bleh = list(allthings.keys())
bleh.sort()
blehh = bleh[-10:]

In [18]:
for blah in blehh:
    print(allthings[blah])

[  4.  24.   5.   2. 199. 949. 601.  72. 103.  41.]
[   4.   23.    6.    5.  339. 1125.  297.  103.   33.   65.]
[  15.   58.   36.   31.  344. 1288.  184.   17.   18.    9.]
[ 21.  11.  26.  60. 715. 754. 346.  42.  22.   3.]
[  38.    9.   13.   11.  227.  537. 1139.   12.    6.    8.]
[ 11.   5.  25.  44. 791. 709. 346.  20.  40.   9.]
[  10.   18.   78.    5.    5. 1737.    8.   43.   68.   28.]
[  5.  11.  16.  42. 322. 945. 547.  40.  57.  15.]
[ 11.  30.   3.  56.  20. 874. 956.  15.  19.  16.]
[   5.   21.   53.    6.   82. 1590.  108.  117.   14.    4.]


In [20]:
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=1)
for blah in blehh:
    fig.add_trace(go.Scatter(x = [i+1 for i in range(10)], y = allthings[blah], mode = "markers + lines", name = "Profit: " + str(blah)))
fig.show()

In [79]:
NUM_BEBS = 2000

buses = np.random.dirichlet(np.ones(10), size=10000)
for i in range(len(buses)):
    buses[i] = [round(x*(NUM_BEBS-10))+1 for x in buses[i]]

buses = [x for x in buses if sum(x) == NUM_BEBS]

def model(GRANT, AVG_DISTANCE, DISCOUNT_RATE, DIESEL_COST, DIESEL_EFFICIENCY, DIESEL_FUEL_PRICE,
        DIESEL_FUEL_INCREASE, DIESEL_MAINTENANCE, BEB_COST, BEB_EFFICIENCY, BEB_FUEL_PRICE,
        BEB_MAINTENANCE, BEB_FUEL_INCREASE, BEB_DEMAND_CHARGE, BEB_RESALE, CHARGER_COST, 
        CHARGER_INSTALLATION, CHARGER_PEAK_DRAW, YEARS, ENVIRONMENT):
    # LIFETIME = 12
    CHARGER_EFFICIENCY = 0.9
    dcf = 0

    dcf = ((DIESEL_COST-BEB_COST) - CHARGER_COST - CHARGER_INSTALLATION + min((BEB_COST + CHARGER_COST + CHARGER_INSTALLATION)/2, GRANT))  # upfront costs 
    # dcf += NUM_BEBS * (DIESEL_COST*DIESEL_RESALE)
    # print(dcf)
    for year in range(YEARS):
        projected_discount = (1+DISCOUNT_RATE)**year
        maintenance = (DIESEL_MAINTENANCE-BEB_MAINTENANCE)*AVG_DISTANCE
        fuel = (DIESEL_EFFICIENCY*DIESEL_FUEL_PRICE*((1+DIESEL_FUEL_INCREASE)**year)
                -(2-CHARGER_EFFICIENCY)*BEB_EFFICIENCY*BEB_FUEL_PRICE*((1+BEB_FUEL_INCREASE)**year))*AVG_DISTANCE
        demand = CHARGER_PEAK_DRAW*BEB_DEMAND_CHARGE
        dcf += (maintenance+fuel-demand)/projected_discount
        
        # print("Year:", year+1, "DCF:", dcf)

    #  print(dcf)
    dcf += ((BEB_COST*BEB_RESALE))/(1+DISCOUNT_RATE**YEARS)
    return dcf

GRANT_TOTAL = 10000000

out = []

for sample in buses: 
    current = 0
    total = 0 
    values = {
        'GRANT': 375000,
        'AVG_DISTANCE': 26980.64,
        'DISCOUNT_RATE': 0.0249,
        'DIESEL_COST': 435000,
        'DIESEL_EFFICIENCY': 0.227,
        'DIESEL_FUEL_PRICE': 4.366,
        'DIESEL_FUEL_INCREASE': 0.014,
        'DIESEL_MAINTENANCE': 0.49,
        'BEB_COST': 770000 ,
        'BEB_EFFICIENCY': 2.15,
        'BEB_FUEL_PRICE': 0.1256,
        'BEB_MAINTENANCE': 0.14,
        'BEB_FUEL_INCREASE': 0.024,
        'BEB_DEMAND_CHARGE': 3.45,
        'BEB_RESALE': 0.15,
        'CHARGER_COST': 50000,
        'CHARGER_INSTALLATION': 17050,
        'CHARGER_PEAK_DRAW': 70,
        'YEARS': 10,
        'ENVIRONMENT': 1
    }
    
    for amount in sample:
        current += amount
        values['GRANT'] = GRANT_TOTAL/amount
        total += amount * model(*values.values())
        values['DIESEL_FUEL_PRICE'] *= (1+values['DIESEL_FUEL_INCREASE'])
        values['BEB_FUEL_PRICE'] *= (1+values['BEB_FUEL_INCREASE'])
        values['BEB_COST'] *= 0.975
        values['YEARS'] -= 1
        values['ENVIRONMENT'] *= (0.90 + 0.1*(current/NUM_BEBS))

    out.append(total)

optimal = np.array([x for _, x in sorted(zip(out, buses))][-10::])
print(optimal.mean(axis=0))
print([round(x) for x in optimal.mean(axis=0)])

[706.7 475.2 174.1 173.8 101.1 104.   71.2  73.7  85.2  35. ]
[707, 475, 174, 174, 101, 104, 71, 74, 85, 35]


In [106]:
NUM_BEBS = 2000

buses = np.random.dirichlet(np.ones(10)*5, size=20000)
for i in range(len(buses)):
    buses[i] = [round(x*(NUM_BEBS-10))+1 for x in buses[i]]

buses = [x for x in buses if sum(x) == NUM_BEBS]



def model(GRANT, AVG_DISTANCE, DISCOUNT_RATE, DIESEL_COST, DIESEL_EFFICIENCY, DIESEL_FUEL_PRICE,
          DIESEL_FUEL_INCREASE, DIESEL_MAINTENANCE, BEB_COST, BEB_EFFICIENCY, BEB_FUEL_PRICE,
          BEB_MAINTENANCE, BEB_FUEL_INCREASE, BEB_DEMAND_CHARGE, BEB_RESALE, CHARGER_COST, 
          CHARGER_INSTALLATION, CHARGER_PEAK_DRAW, YEARS, ENVIRONMENT):
    # LIFETIME = 12
    CHARGER_EFFICIENCY = 0.9
    dcf = 0

    dcf = ((DIESEL_COST-BEB_COST) - CHARGER_COST - CHARGER_INSTALLATION + GRANT)  # upfront costs 
    # dcf += NUM_BEBS * (DIESEL_COST*DIESEL_RESALE)
    # print(dcf)
    for year in range(YEARS):
        projected_discount = (1+DISCOUNT_RATE)**year
        maintenance = (DIESEL_MAINTENANCE-BEB_MAINTENANCE)*AVG_DISTANCE
        fuel = (DIESEL_EFFICIENCY*DIESEL_FUEL_PRICE*((1+DIESEL_FUEL_INCREASE)**year)
                -(2-CHARGER_EFFICIENCY)*BEB_EFFICIENCY*BEB_FUEL_PRICE*((1+BEB_FUEL_INCREASE)**year))*AVG_DISTANCE
        demand = CHARGER_PEAK_DRAW*BEB_DEMAND_CHARGE
        dcf += (maintenance+fuel-demand)/projected_discount
        
        # print("Year:", year+1, "DCF:", dcf)
        
    #  print(dcf)
    dcf += ((BEB_COST*BEB_RESALE))/(1+DISCOUNT_RATE**YEARS)
    return dcf



GRANT_TOTAL = 10000000

out = []

for sample in buses: 
    total = 0 
    current = 0
    
    values = {
        'GRANT': 375000,
        'AVG_DISTANCE': 26980.64,
        'DISCOUNT_RATE': 0.0249,
        'DIESEL_COST': 435000,
        'DIESEL_EFFICIENCY': 0.227,
        'DIESEL_FUEL_PRICE': 4.366,
        'DIESEL_FUEL_INCREASE': 0.014,
        'DIESEL_MAINTENANCE': 0.49,
        'BEB_COST': 770000 ,
        'BEB_EFFICIENCY': 2.15,
        'BEB_FUEL_PRICE': 0.1256,
        'BEB_MAINTENANCE': 0.14,
        'BEB_FUEL_INCREASE': 0.024,
        'BEB_DEMAND_CHARGE': 3.45,
        'BEB_RESALE': 0.15,
        'CHARGER_COST': 50000,
        'CHARGER_INSTALLATION': 17050,
        'CHARGER_PEAK_DRAW': 70,
        'YEARS': 10,
        'ENVIRONMENT': 1
    }
    
    for amount in sample:
        current += amount
        # values['GRANT'] = GRANT_TOTAL/amount
        total += amount * model(*values.values())*values['ENVIRONMENT']
        values['DIESEL_FUEL_PRICE'] *= (1+values['DIESEL_FUEL_INCREASE'])
        values['BEB_FUEL_PRICE'] *= (1+values['BEB_FUEL_INCREASE'])
        values['BEB_COST'] *= 0.975
        values['YEARS'] -= 1
        values['ENVIRONMENT'] *= (0.90 + 0.1*(current/NUM_BEBS))
    
    out.append(total)

optimal = np.array([x for _, x in sorted(zip(out, buses))][-100::])
print(optimal.mean(axis=0))
print([round(x) for x in optimal.mean(axis=0)])


227272.72727272726
418525.0


138888.88888888888
408900.0


64935.06493506493
399515.625


303030.30303030304
390365.859375


42735.042735042734
381444.837890625


17574.69244288225
372746.84194335935


109890.10989010989
364266.29589477537


54945.054945054944
355997.763497406


27624.309392265193
347935.94440997083


38610.03861003861
340075.67079972156


149253.73134328358
418525.0


71942.44604316547
408900.0


32051.28205128205
399515.625


400000.0
390365.859375


94339.62264150943
381444.837890625


238095.2380952381
372746.84194335935


24813.89578163772
364266.29589477537


39370.07874015748
355997.763497406


39062.5
347935.94440997083


25252.52525252525
340075.67079972156


41666.666666666664
418525.0


238095.2380952381
408900.0


53763.44086021505
399515.625


909090.9090909091
390365.859375


61728.39506172839
381444.837890625


68965.5172413793
372746.84194335935


36363.63636363636
364266.29589477537


12804.097311139565
355997.763497406


106382.97872340426
347935.94